export interface VisualIdentityPalette {
  name: string;
  primary_color: string;
  secondary_color: string;
  hero_background_color: string;
  footer_bg_color: string;
  footer_text_primary: string;
  footer_text_secondary: string;
}

export const VISUAL_IDENTITY_PALETTES: VisualIdentityPalette[] = [
  {
    name: 'Élégance Sombre',
    hero_background_color: '#1a1a1a',
    primary_color: '#d4af37',
    secondary_color: '#b8941e',
    footer_bg_color: '#0f0f0f',
    footer_text_primary: '#ffffff',
    footer_text_secondary: '#d4af37',
  },
  {
    name: 'Classique Neutre',
    hero_background_color: '#ecf0f1',
    primary_color: '#2c3e50',
    secondary_color: '#34495e',
    footer_bg_color: '#2c3e50',
    footer_text_primary: '#ffffff',
    footer_text_secondary: '#bdc3c7',
  },
  {
    name: 'Chaleur Terracotta',
    hero_background_color: '#f4f1de',
    primary_color: '#e07a5f',
    secondary_color: '#c86e56',
    footer_bg_color: '#3d405b',
    footer_text_primary: '#f4f1de',
    footer_text_secondary: '#e07a5f',
  },
  {
    name: 'Forêt Moderne',
    hero_background_color: '#d8f3dc',
    primary_color: '#2d6a4f',
    secondary_color: '#1b4332',
    footer_bg_color: '#1b4332',
    footer_text_primary: '#ffffff',
    footer_text_secondary: '#95d5b2',
  },
  {
    name: 'Océan Profond',
    hero_background_color: '#caf0f8',
    primary_color: '#0077b6',
    secondary_color: '#023e8a',
    footer_bg_color: '#03045e',
    footer_text_primary: '#ffffff',
    footer_text_secondary: '#90e0ef',
  },
  {
    name: 'Luxe Bordeaux',
    hero_background_color: '#f8e8e8',
    primary_color: '#9d0208',
    secondary_color: '#6a040f',
    footer_bg_color: '#370617',
    footer_text_primary: '#ffffff',
    footer_text_secondary: '#dc2f02',
  },
  {
    name: 'Minimaliste Clair',
    hero_background_color: '#ffffff',
    primary_color: '#495057',
    secondary_color: '#343a40',
    footer_bg_color: '#f8f9fa',
    footer_text_primary: '#212529',
    footer_text_secondary: '#6c757d',
  },
  {
    name: 'Sunset Tropical',
    hero_background_color: '#ffe66d',
    primary_color: '#ff6b6b',
    secondary_color: '#ee5a6f',
    footer_bg_color: '#4ecdc4',
    footer_text_primary: '#ffffff',
    footer_text_secondary: '#ffe66d',
  },
  {
    name: 'Café Crème',
    hero_background_color: '#f5deb3',
    primary_color: '#8b4513',
    secondary_color: '#654321',
    footer_bg_color: '#3e2723',
    footer_text_primary: '#f5deb3',
    footer_text_secondary: '#d7ccc8',
  },
  {
    name: 'Nature Zen',
    hero_background_color: '#f1f8e9',
    primary_color: '#7cb342',
    secondary_color: '#558b2f',
    footer_bg_color: '#33691e',
    footer_text_primary: '#ffffff',
    footer_text_secondary: '#aed581',
  },
  {
    name: 'Métropolitain',
    hero_background_color: '#cfd8dc',
    primary_color: '#546e7a',
    secondary_color: '#37474f',
    footer_bg_color: '#263238',
    footer_text_primary: '#ffffff',
    footer_text_secondary: '#b0bec5',
  },
  {
    name: 'Corail Moderne',
    hero_background_color: '#fff5f3',
    primary_color: '#ff6b6b',
    secondary_color: '#ff8787',
    footer_bg_color: '#2d3748',
    footer_text_primary: '#ffffff',
    footer_text_secondary: '#ff8787',
  },
  {
    name: 'Menthe Fraîche',
    hero_background_color: '#f0fdf4',
    primary_color: '#10b981',
    secondary_color: '#059669',
    footer_bg_color: '#064e3b',
    footer_text_primary: '#ffffff',
    footer_text_secondary: '#6ee7b7',
  },
  {
    name: 'Lavande Douce',
    hero_background_color: '#faf5ff',
    primary_color: '#8b5cf6',
    secondary_color: '#7c3aed',
    footer_bg_color: '#4c1d95',
    footer_text_primary: '#ffffff',
    footer_text_secondary: '#c4b5fd',
  },
  {
    name: 'Ambre Chaud',
    hero_background_color: '#fef3c7',
    primary_color: '#f59e0b',
    secondary_color: '#d97706',
    footer_bg_color: '#78350f',
    footer_text_primary: '#ffffff',
    footer_text_secondary: '#fbbf24',
  },
  {
    name: 'Ardoise Urbain',
    hero_background_color: '#f1f5f9',
    primary_color: '#475569',
    secondary_color: '#334155',
    footer_bg_color: '#0f172a',
    footer_text_primary: '#ffffff',
    footer_text_secondary: '#94a3b8',
  },
];
